version: "3"

services:
  rl-proj:
    build: .
    volumes:
      - ./src:/root/src
      - ./paper_code_pyTorch_updated_packages:/root/paper_code_pyTorch_updated_packages
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    tty: true
    privileged: true
    network_mode: "host"
